spring.application.name=order-service
server.port=8083

# localhost or docker
spring.kafka.bootstrap-servers=localhost:9092
#spring.kafka.bootstrap-servers=kafka:9092

spring.kafka.consumer.group-id=default-group
spring.kafka.consumer.auto-offset-reset=earliest

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# Logging
logging.pattern.console=%d{HH:mm:ss} %-5level [%-40.40logger{36}] %msg%n
logging.level.root=INFO
logging.level.org.apache.kafka=WARN
logging.level.org.springframework.kafka=WARN
