spring.application.name=product-service
server.port=8082

spring.data.mongodb.uri=mongodb://localhost:27017/productdb
#spring.data.mongodb.auto-index-creation=true

# Logging
logging.pattern.console=%d{HH:mm:ss} %-5level [%-40.40logger{36}] %msg%n
logging.level.root=INFO
logging.level.org.apache.kafka=WARN
logging.level.org.springframework.kafka=WARN
logging.level.org.mongodb.driver=WARN
logging.level.io.netty=WARN
logging.level.reactor.netty=WARN
